FROM openjdk:8 AS gradle-builder

WORKDIR /app

COPY . .

WORKDIR zuul-server

RUN ../gradlew build

FROM openjdk:8-jre

WORKDIR /root/

COPY --from=gradle-builder /app/zuul-server/build/libs/zuul-server-0.0.1-SNAPSHOT.jar .

CMD ["java","-jar","zuul-server-0.0.1-SNAPSHOT.jar"]