version: "3"
services:
    authorization:
        build: ./authorization

    communication:
        build: ./communication
        depends_on:
            - eureka-server
        command: gradle bootRun

    config-server:
        build: ./config-server
        depends_on:
            - eureka-server

    eureka-server:
        build: ./eureka-server

    zuul-server:
        build: ./zuul-server
        depends_on:
            - eureka-server
        ports:
            - "50000:8080"
