FROM openjdk:8 AS gradle-builder

WORKDIR /app

COPY . .

WORKDIR eureka-server

RUN ../gradlew build

FROM openjdk:8-jre

WORKDIR /root/

COPY --from=gradle-builder /app/eureka-server/build/libs/eureka-server-0.0.1-SNAPSHOT.jar .

CMD ["java","-jar","eureka-server-0.0.1-SNAPSHOT.jar"]