FROM openjdk:8 AS gradle-builder

WORKDIR /app

COPY . .

WORKDIR communication

RUN ../gradlew build

FROM openjdk:8-jre

WORKDIR /root/

COPY --from=gradle-builder /app/communication/build/libs/communication-0.0.1-SNAPSHOT.jar .

CMD ["java","-jar","communication-0.0.1-SNAPSHOT.jar"]