FROM openjdk:8 AS gradle-builder

WORKDIR /app

COPY . .

WORKDIR authorization

RUN ../gradlew build

FROM openjdk:8-jre

WORKDIR /root/

COPY --from=gradle-builder /app/authorization/build/libs/authorization-0.0.1-SNAPSHOT.jar .

CMD ["java","-jar","authorization-0.0.1-SNAPSHOT.jar"]