version: "3.2"
services:
  redis:
    image: redis:4.0.8-alpine
    container_name: redis
    ports:
      - "6379:6379"
  gradle:
    build: .
    container_name: gradle
    ports:
      - "8090:8090"