eureka:
  client:
    fetchRegistry: false
    region: default
    registerWithEureka: false
    registryFetchIntervalSeconds: 5
server:
  port: 8082
spring:
  application:
    name: eureka-server
  redis:
    port: 6379
